### ISSUE TITLE
move https://github.com/joyent/node-http-signature/blob/master/lib/util.js into it's own module?

### ISSUE THREAD

**Issue by dominictarr** [joyent/node-http-signature#18]
Hi, would you consider moving ./lib/util.js into it's own module?
this is quite useful on it's own, independently of http-signature.

Moving it out will make more discoverable (more searches for convert SSH key to PEM will hit it) and modules that need that will be able to use that directly,
and won't have to review unrelated changes in http-signature.

If this was something else, i'd be inclined to refactor and republish this myself, but obviously the security of this particular module is much more important and It's not worth creating a fork just for the sake of a architectural style issue.

**Comment by arekinath** [comment]
Just FYI, we went and made a version of this with a different API so that we could start getting rid of some copy-paste adaptations of this code which have made their way into other modules as well. The new version also supports ECDSA keys (though http-signature doesn't just yet), and a bunch of other useful features -- see https://github.com/arekinath/node-sshpk for more info about it if you're curious.

The functions in util.js have now been replaced with thin wrappers around this API, so I'm gonna mark this issue as closed. Thanks for your time looking at this!
